language: node_js
node_js:
 - "11"

addons:
  chrome: stable

branches:
  only:
    - master

notifactions:
  email: false

before_script:
  - npm run sassBuild:component
  - npm run postCss:component
  - npm run sassRender
  - npm run distJS
  - npm run bundler

script:
  - npm run test:ci

after_success:
  - npx semantic-release

notifications:
  webhooks: https://outlook.office.com/webhook/47d2147c-afa1-4bd4-ae32-2749757844b2@0f44c5d4-42b0-45c2-bf55-d0fea8430d33/TravisCI/6ccc70bb60f948809957cbd7ab063223/c3c71b9e-d319-4002-a79c-b694111e2be8
